In [37]:
import os 
import pandas as pd
import numpy as np
from dotenv import load_dotenv
from sklearn.model_selection import train_test_split

In [43]:
load_dotenv()
mod_train_path = os.getenv('mod_train_path')
mod_val_path = os.getenv('mod_val_path')
train_x_np_path  = os.getenv('train_x_np_path')
train_y_np_path = os.getenv('train_y_np_path')
val_x_np_path = os.getenv('val_x_np_path')
val_y_np_path = os.getenv('val_y_np_path')

In [44]:
traindf = pd.read_csv(mod_train_path)
traindf.sample(frac=1)
traindf[:5]

,Unnamed: 0,X,Y
0,0,[[[0.65490196 0.63921569 0.76862745]\n [0.650...,Apple___Apple_scab
1,1,[[[0.52941176 0.50196078 0.70196078]\n [0.509...,Apple___Apple_scab
2,2,[[[0.04313725 0.00392157 0.05490196]\n [0.172...,Apple___Apple_scab
3,3,[[[0.01960784 0.01960784 0.1254902 ]\n [0.019...,Apple___Apple_scab
4,4,[[[0. 0. 0.]\n [0. 0. 0.]\n [0. 0. 0.]\n .....,Apple___Apple_scab

In [45]:
z = pd.get_dummies(traindf['Y'],dtype=float)
traindf.drop(['Y','Unnamed: 0'],inplace=True,axis=1)
X = np.stack(traindf['X'].values)
Y = z.values

In [46]:
X[:5]

array(['[[[0.65490196 0.63921569 0.76862745]\n  [0.65098039 0.63529412 0.76470588]\n  [0.64705882 0.63137255 0.76078431]\n  ...\n  [0.7254902  0.71372549 0.82745098]\n  [0.71764706 0.70588235 0.81960784]\n  [0.70980392 0.69803922 0.81176471]]\n\n [[0.66666667 0.65098039 0.78039216]\n  [0.6627451  0.64705882 0.77647059]\n  [0.65882353 0.64313725 0.77254902]\n  ...\n  [0.72941176 0.71764706 0.83137255]\n  [0.72156863 0.70980392 0.82352941]\n  [0.71764706 0.70588235 0.81960784]]\n\n [[0.66666667 0.65098039 0.78039216]\n  [0.6627451  0.64705882 0.77647059]\n  [0.65882353 0.64313725 0.77254902]\n  ...\n  [0.7372549  0.7254902  0.83921569]\n  [0.72941176 0.71764706 0.83137255]\n  [0.7254902  0.71372549 0.82745098]]\n\n ...\n\n [[0.39215686 0.35294118 0.48627451]\n  [0.4        0.36078431 0.49411765]\n  [0.40784314 0.36862745 0.50196078]\n  ...\n  [0.49803922 0.43529412 0.54117647]\n  [0.49411765 0.43137255 0.5372549 ]\n  [0.49411765 0.43137255 0.5372549 ]]\n\n [[0.39607843 0.35686275 0.49019608]\n  [0.4        0.36078431 0.49411765]\n  [0.40392157 0.36470588 0.49803922]\n  ...\n  [0.47843137 0.41568627 0.52156863]\n  [0.48235294 0.41960784 0.5254902 ]\n  [0.48235294 0.41960784 0.5254902 ]]\n\n [[0.40784314 0.36862745 0.50196078]\n  [0.40392157 0.36470588 0.49803922]\n  [0.4        0.36078431 0.49411765]\n  ...\n  [0.4745098  0.41176471 0.51764706]\n  [0.47843137 0.41568627 0.52156863]\n  [0.48235294 0.41960784 0.5254902 ]]]',
       '[[[0.52941176 0.50196078 0.70196078]\n  [0.50980392 0.48235294 0.68235294]\n  [0.49411765 0.46666667 0.66666667]\n  ...\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.47843137 0.45882353 0.67843137]]\n\n [[0.51372549 0.48627451 0.68627451]\n  [0.50980392 0.48235294 0.68235294]\n  [0.50980392 0.48235294 0.68235294]\n  ...\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.47843137 0.45882353 0.67843137]]\n\n [[0.50196078 0.4745098  0.6745098 ]\n  [0.51372549 0.48627451 0.68627451]\n  [0.5254902  0.49803922 0.69803922]\n  ...\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.47843137 0.45882353 0.67843137]\n  [0.48235294 0.4627451  0.68235294]]\n\n ...\n\n [[0.19607843 0.13333333 0.23529412]\n  [0.19607843 0.13333333 0.23529412]\n  [0.19215686 0.12941176 0.23137255]\n  ...\n  [0.34117647 0.30980392 0.45490196]\n  [0.34901961 0.31764706 0.4627451 ]\n  [0.35294118 0.32156863 0.46666667]]\n\n [[0.18039216 0.12156863 0.21176471]\n  [0.18039216 0.12156863 0.21176471]\n  [0.18039216 0.12156863 0.21176471]\n  ...\n  [0.34117647 0.31372549 0.44705882]\n  [0.34509804 0.31764706 0.45098039]\n  [0.34901961 0.32156863 0.45490196]]\n\n [[0.16862745 0.10980392 0.2       ]\n  [0.16862745 0.10980392 0.2       ]\n  [0.16470588 0.10588235 0.19607843]\n  ...\n  [0.34117647 0.31372549 0.44705882]\n  [0.34509804 0.31764706 0.45098039]\n  [0.34509804 0.31764706 0.45098039]]]',
       '[[[0.04313725 0.00392157 0.05490196]\n  [0.17254902 0.11372549 0.18431373]\n  [0.18431373 0.1254902  0.20784314]\n  ...\n  [0.50980392 0.48235294 0.68235294]\n  [0.50588235 0.47843137 0.67843137]\n  [0.50588235 0.47843137 0.67843137]]\n\n [[0.04313725 0.00392157 0.05490196]\n  [0.17254902 0.11372549 0.18431373]\n  [0.18431373 0.1254902  0.20784314]\n  ...\n  [0.52156863 0.49411765 0.69411765]\n  [0.51372549 0.48627451 0.68627451]\n  [0.50980392 0.48235294 0.68235294]]\n\n [[0.03921569 0.00392157 0.05098039]\n  [0.16862745 0.11372549 0.18039216]\n  [0.18431373 0.1254902  0.20784314]\n  ...\n  [0.53333333 0.50588235 0.70588235]\n  [0.52156863 0.49411765 0.69411765]\n  [0.50980392 0.48235294 0.68235294]]\n\n ...\n\n [[0.01568627 0.01176471 0.09411765]\n  [0.34117647 0.31764706 0.41960784]\n  [0.3372549  0.30980392 0.42352941]\n  ...\n  [0.47843137 0.45882353 0.67843137]\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.4745098  0.45490196 0.6745098 ]]\n\n [[0.01568627 0.01176471 0.09411765]\n  [0.34509804 0.32156863 0.42352941]\n  [0.34117647 0.31372549 0.42745098]\n  ...\n  [0.47843137 0.45882353 0.67843137]\n  [0.4745098  0.45490196 0.6745098 ]\n  [0.4745098  0.45490196 0.6745098 ]]\n\n [[0.01960784 0.01176471 0.09803922]\n  [0.34901961 0.3254902  0.42745098]\n  [0.34509804 0.31764706 0.43137255]\n  ...\n  [0.48235294 0.4627451  0.68235294]\n  [0.47843137 0.45882353 0.67843137]\n  [0.4745098  0.45490196 0.6745098 ]]]',
       '[[[0.01960784 0.01960784 0.1254902 ]\n  [0.01960784 0.01960784 0.1254902 ]\n  [0.01960784 0.01960784 0.1254902 ]\n  ...\n  [0.01568627 0.01176471 0.06666667]\n  [0.01568627 0.01176471 0.06666667]\n  [0.01568627 0.01176471 0.06666667]]\n\n [[0.48627451 0.48235294 0.61568627]\n  [0.49019608 0.48627451 0.61960784]\n  [0.49019608 0.48627451 0.61960784]\n  ...\n  [0.36470588 0.34117647 0.42352941]\n  [0.36078431 0.34117647 0.42745098]\n  [0.36078431 0.34117647 0.41960784]]\n\n [[0.46666667 0.45882353 0.61960784]\n  [0.47058824 0.4627451  0.62352941]\n  [0.47058824 0.4627451  0.62352941]\n  ...\n  [0.34117647 0.31764706 0.42352941]\n  [0.34117647 0.31764706 0.43137255]\n  [0.34117647 0.31764706 0.42352941]]\n\n ...\n\n [[0.49803922 0.47058824 0.67058824]\n  [0.50588235 0.47843137 0.67843137]\n  [0.51372549 0.48627451 0.68627451]\n  ...\n  [0.19215686 0.12941176 0.23137255]\n  [0.17647059 0.11764706 0.20784314]\n  [0.16078431 0.10196078 0.19215686]]\n\n [[0.50196078 0.4745098  0.6745098 ]\n  [0.50980392 0.48235294 0.68235294]\n  [0.51764706 0.49019608 0.69019608]\n  ...\n  [0.19607843 0.13333333 0.23529412]\n  [0.18039216 0.12156863 0.21176471]\n  [0.16470588 0.10588235 0.19607843]]\n\n [[0.50980392 0.48235294 0.68235294]\n  [0.51372549 0.48627451 0.68627451]\n  [0.52156863 0.49411765 0.69411765]\n  ...\n  [0.19607843 0.13333333 0.23529412]\n  [0.18431373 0.1254902  0.21568627]\n  [0.16862745 0.10980392 0.2       ]]]',
       '[[[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]\n\n [[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]\n\n [[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]\n\n ...\n\n [[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]\n\n [[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]\n\n [[0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]\n  ...\n  [0. 0. 0.]\n  [0. 0. 0.]\n  [0. 0. 0.]]]'],
      dtype='<U1385')

In [47]:
Y[:5]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [48]:
np.save(train_x_np_path,X)
np.save(train_y_np_path,Y)

In [49]:
valdf = pd.read_csv(mod_val_path)
valdf.sample(frac=1)
valdf[:5]

,Unnamed: 0,X,Y
0,0,[[[0.65490196 0.63921569 0.76862745]\n [0.650...,Apple___Apple_scab
1,1,[[[0.52941176 0.50196078 0.70196078]\n [0.509...,Apple___Apple_scab
2,2,[[[0.04313725 0.00392157 0.05490196]\n [0.172...,Apple___Apple_scab
3,3,[[[0.01960784 0.01960784 0.1254902 ]\n [0.019...,Apple___Apple_scab
4,4,[[[0. 0. 0.]\n [0. 0. 0.]\n [0. 0. 0.]\n .....,Apple___Apple_scab

In [50]:
z = pd.get_dummies(valdf['Y'],dtype=float)
valdf.drop(['Y','Unnamed: 0'],inplace=True,axis=1)
X = np.stack(valdf['X'].values)
Y = z.values

In [51]:
np.save(val_x_np_path,X)
np.save(val_y_np_path,Y)